# Generated by Django 4.2.7 on 2023-11-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='USERNAME',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
