# Generated by Django 4.2.7 on 2023-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Event_Image',
            field=models.ImageField(null=True, upload_to='Event_Images/'),
        ),
        migrations.AddField(
            model_name='events',
            name='Event_Poster',
            field=models.ImageField(null=True, upload_to='Event_Posters'),
        ),
    ]
