# Generated by Django 4.2.7 on 2023-11-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_events_event_image_events_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Place',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
