# Generated by Django 4.2.7 on 2023-11-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_events_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Tickets_Price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='Total_Ticket',
            field=models.BigIntegerField(),
        ),
    ]
