# Generated by Django 4.2.7 on 2023-11-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_events_tickets_price_alter_events_total_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=64)),
                ('BookingCode', models.CharField(max_length=10)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=64)),
                ('Phone', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=20)),
                ('Postal_code', models.CharField(max_length=8)),
                ('State', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=10)),
                ('NameOnCard', models.CharField(max_length=50)),
                ('CreditCardType', models.CharField(max_length=20)),
                ('CreditCardNumber', models.CharField(max_length=20)),
                ('CvvCode', models.CharField(max_length=3)),
                ('CardExpirationDate', models.CharField(max_length=10)),
                ('EventName', models.CharField(max_length=100)),
                ('TicketPrice', models.BigIntegerField()),
                ('NumberOfTickets', models.BigIntegerField()),
            ],
        ),
    ]
